const Article1 = () => (
  <div className="container" style={{width: '100%'}}>
    <h2>Recovery Following an Ironman Triathlon: A Case Study</h2>
    <p className="authors">Kazunori Nosaka, Chris R. Abbiss, Greig Watson, Bradley Wall, Katushiko Suzuk, and Paul Laursen</p>
    <p className="affiliation">School of Exercise Biomechanics and Health Sciences, Edith Cowan University, Joondalup, WA Australia, and Faculty of Sports Sciences, Waseda University, Tokorozawa, Japan.</p>
    <p className="journal">African International Journal of Educational Learning, Vol. 12, June. 2025</p>
    
    <h3>Abstract</h3>
    <p className="abstract">Completion of an Ironman triathlon results in muscle damage, indicated by reductions in muscle function and muscle soreness. However, the time course of recovery from this damage has received little attention. The purpose of this case study was to examine the time course of changes in blood markers of muscle damage and inflammation, muscle function, muscle soreness, and economy of motion following an Ironman event. An experienced well-trained male triathlete aged 35 years completed the Western Australian Ironman triathlon in 11 h 38 min 41 s (winner's time: 8 h 3 min 56 s). Before and on several occasions in the 15 days after the event, the participant performed an incremental cycling test to exhaustion, running economy test at 12 km/h (2% incline), maximal isometric knee flexion and extension at 90° knee flexion, and maximal squat and countermovement jumps. Venous blood samples and muscle soreness were also assessed. Maximal oxygen consumption, efficiency of motion, maximal muscle strength, and jump performance were all markedly reduced (4.5–54%) following the event, but returned to baseline within 15, 8, 2, and 8 days following the event, respectively. Muscle soreness and blood markers peaked 2–24 h after the race but returned to baseline within 8 days. In conclusion, although the Ironman triathlon induces marked muscle damage, a trained triathlete recovered almost completely within approximately one week, without the use of any therapeutic interventions after the event.</p>
    
    <div className="keywords">
      <strong>Keywords:</strong> <em>Muscle damage, muscle soreness, muscle strength, running economy, cycling efficiency</em>
    </div>
    <h3>Introduction</h3>
    <p>The long distances that comprise an Ironman triathlon (3.8-km swim, 180-km cycle, 42.2-km run) create a challenge that can induce significant physical and psychological stress on its participants (Farber, Schaefer, Franey, Grimaldi, & Hill, 1991; Lepers, 2008). One of the revealing signs of this physical toll is the amount of muscle damage it inflicts. For example, we have shown reductions in muscle strength and jump height, together with increases in muscle soreness, blood markers of muscle damage, and inflammation in the 24 h following an Ironman triathlon (Suzuki et al., 2006). While the acute phase response has been documented, the time course of the recovery from muscle damage induced during an Ironman triathlon is less clear. Only Neubauer and colleagues (Neubauer, König, & Wagner, 2008) have outlined the recovery 1, 5, and 19 days after an Ironman race. They showed a pronounced initial systemic inflammatory response together with persistent low-grade systemic inflammation for up to 5 days after the event, reflecting incomplete recovery. Although all measured variables had returned to baseline values within 19 days, a more precise understanding of the time course of recovery to baseline values, together with functional measurements, is required. It is important for sport medicine professionals to understand the recovery process associated with this popular but challenging event.</p>
    <br/>
    
    <p>There is also limited information available concerning the effects that muscle damage and subsequent recovery may have on running economy and maximal oxygen uptake (VO₂max) after an Ironman triathlon. It could be that running economy and VO₂max are reduced for several days, possibly due to neuromuscular fatigue and/or muscle damage; however, no previous studies have investigated this response after an Ironman triathlon.</p>
    <br/>

    <p>We had the opportunity to collect data on blood markers of muscle damage and inflammation, muscle function, muscle soreness, running economy, and VO₂max for a male triathlete while cycling, before and for 15 days after an Ironman event. These data show that recovery from an Ironman triathlon race by an experienced triathlete is almost complete within a week of finishing the event.</p>

    <h3>Methods</h3>
    <h4>Participant</h4>
    <p>Our experienced male triathlete (age 35 years, body mass 75.0 kg, stature 1.78 m, VO₂max 67.0 ml·kg⁻¹·min⁻¹) participated in the Ironman Western Australia event (Busselton, Western Australia) on 1 December 2006. This was the participant's eleventh Ironman triathlon (personal best time: 10 h 14 min). Before testing, the participant was informed of the risks associated with the study and provided written informed consent in accordance with the Institutional Human Research Ethics Committee. He completed the race in 11 h 38 min 41 s, in which the swimming (1 h 7 min 3 s) and cycling (5 h 25 min 6 s) legs were performed as expected, but his run (5 h 6 min 31 s) was about an hour slower than expected. This was due to fatigue related to hyperthermia and muscle cramping near the half-way point of the run. In total, 804 athletes participated in the event, of whom 766 completed the course, and the winner's time was 8 h 3 min 56 s. Our participant finished 331st, and his relative time to that of the winner was 144%.</p>
    <br />

    <h4>Experimental overview</h4>
    <p>The participant attended the laboratory one week before (Pre 1) and on seven separate occasions in the 15 days after the Ironman event. The participant also attended a makeshift laboratory the day before (Pre 2), and 2 and 12 h after, the event.</p>
    <br />

    {/* <h1>THERE WILL BE AN IMAGE HERE. Below is a sample</h1> */}
    <div style={{display: 'flex', justifyContent: 'center'}}>
        <img
          src="https://res.cloudinary.com/dyzwnfpje/image/upload/v1757448017/article-1_image_je9wuj.png"
          alt="Ironman Triathlon"
          style={{maxWidth: '500px', width: '100%', height: 'auto', borderRadius: '8px'}}
          className="responsive-img"
        />
    </div>
     <br />

    <p>Figure 1. Schematic time line of measurements before and after the Ironman triathlon event.</p>
    <br />

    <p>The variables measured during the study are outlined below.</p>

    <p>Maximal oxygen consumption, gross cycling efficiency, and running economy</p>
    <p>Once before and on three separate occasions after the Ironman event, the participant performed an incremental cycling test to exhaustion and a submaximal running economy test under controlled laboratory conditions (20–22°C and 40–50% relative humidity). The incremental cycling test was conducted on an electromagnetic cycle ergometer (Velotron; Racer Mate, Seattle, WA), and the running economy test was conducted on a motorized treadmill (HUR, GAS Fitness Systems, Carrollton, TX). Throughout both tests, expired gases were analysed for concentration and volume using a calibrated and validated Parvo Medics True One 2400 diagnostic system (Sandy, UT).</p>

    <p>The exercise protocol, determination of oxygen consumption (VO₂), and maximal aerobic power output during the incremental cycling test were completed as previously described (Abbiss et al., 2008). Briefly, the participant began cycling at 100 W for 5 min, after which power output was increased by 50 W every 5 min until the participant reached volitional exhaustion. The metabolic cart recorded heart rate throughout the test with the use of a compatible heart rate monitor (Polar Electro Oy, Kempele, Finland). Average VO₂ for the last minute of 100, 150, and 200 W was used as steady-state oxygen consumption for the determination of gross cycling efficiency (Gaesser & Brooks, 1975). During the running economy test, the participant performed a 5-min warm-up running at 8 km·h⁻¹ followed by 5 min at 12 km·h⁻¹ on the motorized treadmill set at a 2% incline (Palazzetti, Margaritis, & Guezennec, 2005). Average VO₂ (litres min⁻¹) over the final minute of the 12 km·h⁻¹ stage was used to determine running economy. Rating of perceived exertion (RPE) and muscle soreness were recorded 1 min before completion of each 5-min stage during the running economy test.</p>
    <br />

    <h4>Muscle function</h4>
    <p>Muscle strength of the knee extensors and flexors, and vertical jump height of the squat and countermovement jumps, were assessed as previously described (Suzuki et al., 2006) on two separate occasions before and on eight occasions after the Ironman event. Briefly, maximal isometric strength of the knee extensors and knee flexors was measured using a strain gauge (Bongshin Loadcell Co. Ltd., Model DBBP 200, South Korea) attached to a wire with a belt that surrounded the ankle joint with the knee joint angle set at 90°. Peak maximal voluntary contraction force was displayed on a digital indicator (Rinstrum Pty. Ltd., Model 2100EX, Brisbane, QLD) connected to the strain gauge, and the higher value of the two measurements was used for further analysis. Grip strength was measured using a Smedley grip dynamometer (Takei Scientific Instruments Co. Ltd., Model TKK5001, Niigata City, Japan) twice for each arm, and the higher value was used to calculate the average value of two arms, which was used for further analysis.</p>
    <br />

    <p>Vertical jump height of the squat jump and countermovement jump was assessed using a leap meter (Takei Scientific Instrument, Japan). For the squat jump, the participant was asked to jump after holding his knee joint at 90° for at least 2 s and without using his arms (held on their hips). The same arm position was used for the countermovement jump, but the participant began the jump motion from a standing position with a countermovement. After two practice jumps, two trials for each jump were performed, and the higher value of the two was used for further analysis.</p>
    <br />

    <h4>Muscle soreness</h4>
    <p>Muscle soreness was assessed using a verbal rating scale of 0 ("no pain") to 10 ("maximal") that has been used previously (Suzuki et al., 2006). The participant was asked to rate his subjective level of soreness on a questionnaire sheet while actively moving specific muscles as instructed (squat, stretching or running) or while the investigator palpated those muscles. Muscle groups of the limbs and trunk assessed included the deltoid, pectoralis, biceps brachii/brachialis, triceps brachii, brachioradialis, rectus/obliquus abdominis, quadriceps femoris, biceps femoris, gastrocnemius/soleus, and low back muscles.</p>
    <br />

    <h4>Blood sampling and analyses</h4>
    <p>Before and on 10 occasions after the Ironman event, approximately 8 ml of blood were taken from the antecubital vein via standard venepuncture techniques. Post-race blood samples were taken within 10 min of completing the event, with the participant lying supine in the medical tent. The blood samples were allowed to clot and centrifuged for 10 min to obtain serum. Serum samples were frozen and stored at −80°C until analysis.</p>
    <br />

    <p>Serum samples were analysed for the following markers of muscle damage and inflammation: creatine kinase (CK), creatine kinase isoenzymes (CK-MM, CK-MB), myoglobin, lactate dehydrogenase, alanine aminotransferase, aspartate aminotransferase, C-reactive protein, and serum amyloid protein A. All of these variables except myoglobin and serum amyloid protein A were analysed using an automated analyser (Model 7450 or Model 7170, Hitachi, Japan). Serum amyloid protein A was analysed using a different automated analyser (Model JCA-BM21, JOEL Ltd., Japan) and myoglobin was analysed using ELISA (Life Diagnostics, West Chester, PA, USA). Serum cytokine concentrations of interleukin-6 (IL-6), IL-10, and IL-1ra were measured with ELISA kits (IL-6: Quantikine HS, R&D Systems, Minneapolis, MN; IL-10: OptEIA, BD Biosciences, San Jose, CA; IL-1ra: Quantikine, R&D Systems). In addition to these blood markers, a portable blood-gas electrolyte analyser (i-STAT Corporation, East Windsor, NJ) was used to measure pH, partial pressure of carbon dioxide, partial pressure of oxygen, lactate concentration, bicarbonate, oxygen saturation, sodium, potassium, chloride, urea, glucose, haemoglobin concentration, and haematocrit before, immediately after, and 2, 12, and 24 h after the race. The results of these measures are not reported here, but haemoglobin and haematocrit were used to calculate changes in plasma volume.</p>

    <h3>Results</h3>
    <h4>Maximal oxygen consumption, gross cycling efficiency, and running economy</h4>
    <p>Both running economy and gross cycling efficiency were reduced (6.5% and 4.5%, respectively) following the event but returned to baseline by 4 and 8 days, respectively. Maximal aerobic power output and VO₂max were reduced by 8.3% (352.5 W to 332.5 W) and 9.5% at 3 days following the event, respectively, but returned to baseline values by day 15. Maximal heart rate decreased by 3% (191 to 185 beats min⁻¹) at 3 days following the event, but returned to baseline by day 8 (193 beats min⁻¹). Rating of perceived exertion while running at 8 km·h⁻¹ and 12 km·h⁻¹ during the running economy test increased in the 48 h following the event (from 8 to 15 and 11 to 18, respectively), but returned to baseline by day 8.</p>
    <br />

    <h4>Muscle function</h4>
    <p>Maximal isometric strength of the knee extensors and knee flexors was reduced by 50% at 2 h following the event, and maximal grip strength was reduced by 26% at 2 h following the event. Maximal isometric strength of the knee extensors and knee flexors and maximal grip strength returned to baseline by 48 h post-race. Squat jump and countermovement jump performance also declined by 50% following the event, improved by 24 h and 48 h post-event, and returned to baseline values within 8 days.</p>
    <p>(Figure 3). </p>
    
    <br />
    <div style={{display: 'flex', justifyContent: 'center'}}>
        <img 
          src="https://res.cloudinary.com/dyzwnfpje/image/upload/v1757449174/article-1_image2_uf9ngl.png"
          alt=""
          style={{maxWidth: '500px', width: '100%', height: 'auto', borderRadius: '8px'}}
          className="responsive-img"
        />
      </div>
      <br />

    <h4>Muscle soreness</h4>
    <p>Muscle soreness developed mainly in the lower limb muscles. The knee extensors recorded the highest pain at 3 days post-event, followed closely by the ankle plantarflexors, lower back, and knee flexors. Moderate muscle soreness was reported in other muscles, including the elbow extensors, upper back, deltoid, and abdominal muscles. The muscle soreness reported while running at 8 km·h⁻¹ and 12 km·h⁻¹ increased markedly at 48 h post-event, but returned to baseline within 8 days.</p>
    <br />

    <h4>Blood markers</h4>
    <p>Plasma volume estimated from haemoglobin and haematocrit immediately after and 2 and 12 h after the race was 7.9%, 4.2%, and 2.9% less than that of the pre-race volume; however, this was not seen at 24 h post-race. The activity of all measured enzymes increased after the race, and peaked between 2 and 24 h post race. Creatine kinase isoenzymes (CK-MM, CK-MB) peaked 2 h after the race and returned to pre-race values within 8 days. Compared with the large increase in creatine kinase (40-fold increase from baseline), the magnitude of increase in aspartate aminotransferase, alanine aminotransferase, and lactate dehydrogenase was small; however, all exceeded the normal reference range after the race. Myoglobin showed the largest magnitude of increase (170-fold increase from baseline), peaked immediately after the race, and returned to baseline within 8 days. Fifteen days after the race, creatine kinase and myoglobin increased from their 8-day post-race values, probably in response to the participant's return to training (he performed a 10-km run and weight-lifting session 3 days before this blood test). C-reactive protein and serum amyloid protein A increased immediately after the race. The highest value for C-reactive protein was observed 24 h after the race and for serum amyloid protein A 48 h after the race; both markers remained elevated above baseline values 8 days post-race. Interleukin-6, IL-10, and IL-1ra also increased after the race, peaked immediately after to 2 h post-race, and returned to baseline within 72 h. The decrease in plasma volume accounted in part (i.e. 8%) for the increases in the measures after the race, at least for 12 h. 
    </p>


  <div className="table-container responsive-table-scroll" style={{overflowX: 'auto', margin: '20px 0', WebkitOverflowScrolling: 'touch'}}>
      <h5>Table 1: Muscle soreness during palpation of the indicated muscle and while running before (pre) and on nine separate occasions in the 15 days after the Ironman triathlon</h5>
      <table style={{width: '100%', borderCollapse: 'collapse', fontSize: '14px'}}>
        <thead>
          <tr style={{backgroundColor: '#f0f0f0'}}>
            <th style={{border: '1px solid #ccc', padding: '8px', textAlign: 'left'}}>Muscle Group</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>Pre</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>2h</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>12h</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>24h</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>2 days</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>3 days</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>4 days</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>5 days</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>8 days</th>
            <th style={{border: '1px solid #ccc', padding: '8px'}}>15 days</th>
          </tr>
        </thead>
        <tbody>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Knee extensor</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>7</td><td style={{border: '1px solid #ccc', padding: '8px'}}>8</td><td style={{border: '1px solid #ccc', padding: '8px'}}>8</td><td style={{border: '1px solid #ccc', padding: '8px'}}>8</td><td style={{border: '1px solid #ccc', padding: '8px'}}>7</td><td style={{border: '1px solid #ccc', padding: '8px'}}>4</td><td style={{border: '1px solid #ccc', padding: '8px'}}>2</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Knee flexors</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>5</td><td style={{border: '1px solid #ccc', padding: '8px'}}>4</td><td style={{border: '1px solid #ccc', padding: '8px'}}>3</td><td style={{border: '1px solid #ccc', padding: '8px'}}>2</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Calf</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>6</td><td style={{border: '1px solid #ccc', padding: '8px'}}>4</td><td style={{border: '1px solid #ccc', padding: '8px'}}>4</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Hip</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>5</td><td style={{border: '1px solid #ccc', padding: '8px'}}>8</td><td style={{border: '1px solid #ccc', padding: '8px'}}>6</td><td style={{border: '1px solid #ccc', padding: '8px'}}>2</td><td style={{border: '1px solid #ccc', padding: '8px'}}>2</td><td style={{border: '1px solid #ccc', padding: '8px'}}>2</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Lower back</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>5</td><td style={{border: '1px solid #ccc', padding: '8px'}}>6</td><td style={{border: '1px solid #ccc', padding: '8px'}}>5</td><td style={{border: '1px solid #ccc', padding: '8px'}}>4</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Upper back</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>5</td><td style={{border: '1px solid #ccc', padding: '8px'}}>4</td><td style={{border: '1px solid #ccc', padding: '8px'}}>3</td><td style={{border: '1px solid #ccc', padding: '8px'}}>3</td><td style={{border: '1px solid #ccc', padding: '8px'}}>2</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Abdominal</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>4</td><td style={{border: '1px solid #ccc', padding: '8px'}}>3</td><td style={{border: '1px solid #ccc', padding: '8px'}}>2</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Shoulder</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>5</td><td style={{border: '1px solid #ccc', padding: '8px'}}>4</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>2</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Elbow flexors</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Elbow extensors</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>5</td><td style={{border: '1px solid #ccc', padding: '8px'}}>3</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>1</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Run at 8 km·h⁻¹</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>5</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>3</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '8px'}}>Run at 12 km·h⁻¹</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>9</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>4</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>-</td><td style={{border: '1px solid #ccc', padding: '8px'}}>0</td></tr>
        </tbody>
      </table>
    </div>

    <h4>Discussion</h4>
    
    <p>The present case study showed that an experienced endurance triathlete can recover from an Ironman triathlon event in approximately one week. In a previous study (Suzuki et al., 2006), we investigated nine well-trained male triathletes for changes in muscle damage and inflammation markers before, immediately after, and one day after an Ironman triathlon where the average total race time was ~10 h. In the present study, it took longer for the athlete to complete the race (11 h 38 min); however, the changes in muscle function, muscle soreness, and blood markers immediately and one day after the race were similar to those reported in the previous study (Suzuki et al., 2006). Neubauer et al. (2008) recently reported changes in blood markers of muscle damage and inflammation immediately after and 1, 5, and 19 days after an Ironman triathlon in 42 well-trained male triathletes (average total race time: 10 h 51 min), and showed similar changes in creatine kinase activity, myoglobin concentration, and IL-6 and IL-lO to those in the present study. Thus, the results of the present study would appear to represent an accurate account of the time course of recovery of these markers 
    in well-trained male triathletes following completion of an Ironman triathlon.</p>
    <br />

    <p>It is well documented that muscle force and power-generating capacity are reduced significantly in the days following exercise resulting in muscle damage (Byrne & Eston, 2002). The reduction in VO2max (Figure 2) observed following the Ironman was coupled with a reduction in maximal aerobic power output. At submaximal workloads, an increase in V02 has been reported after exercise resulting in muscle damage. For instance, economy of motion was shown to be reduced following 30 min of downhill running (Braun & Dutto, 2003; Chen, Nosaka, & Tu, 2007), a marathon (Kyroldinen et al., 2000), a competitive duathlon (Calbet, Chavarren, & Dorado, 2001), or 120 maximal eccentric contractions (Paschalis et al., 2005). To the best of our knowledge, ours is the first study to examine the influence of an Ironman triathlon on economy of motion and its time course of recovery. Interestingly, the magnitude and duration of the recovery running economy in the present study was similar to that observed following 30 min of downhill running (Chen et al., 2007). The increase in V02 observed during the submaximal cycling and running may be the result of decreased muscle function and/or altered lower limb kinematics (Chen et al., 2007; Saunders, Pyne, Telford, & Hawley, 2004). Indeed, the time course of recovery for the maximal voluntary isometric contractions (Figure 3) and biochemical muscle damage markers (Table II) followed a similar pattern to that of running efficiency and cycling economy (Figure 2).</p>
    <br />

    <p>The decreases in muscle function after the Ironman triathlon are likely due to a combination of fatigue and muscle damage. If the decrease in grip strength (e.g. 26% at 2 h post-race) indicates supraspinal fatigue, then supraspinal fatigue would appear to play a partial role in the decrease in muscle function at least in the first 24 h post-event. A precise time course of muscle function recovery following an Ironman triathlon race was not made clear by previous research (Suzuki et a!, 2006). As shown in Figure 3, knee extension and flexion isometric strength returned to baseline after 2 days of recovery, and vertical jump performance recovered within 8 days. Muscle soreness was also alleviated after 8 days of recovery (Table I), and most of the blood markers of muscle damage and inflammation had returned to baseline values by 8 days (Table II).</p>
    <br />

    <p>These findings suggest that muscle damage induced by the Ironman triathlon was repaired within about a week. This was also the case for recovery from maximal eccentric exercise in resistance-trained individuals (Newton et al., 2008) and recovery from downhill running (Chen et al., 2007). Kyroläinen et al. (2000) reported that recovery from a marathon race occurs within a week. From the present case study, it would appear that the time taken for the muscles to recover from an Ironman triathlon is similar to that induced by marathon running. This may be because most muscle damage occurs during the run phase, and that the level of muscle damage caused by the swimming and cycling phases is minimal due to the lower number and intensity of lengthening contractions.</p>
    <br />

    <p>Considering the recovery of aerobic performance markers (VO2max, cycling efficiency, and running economy), it may be theoretically possible to perform training at maximal intensity 2 weeks after an Ironman triathlon race. In fact, the athlete in the present study started training 10 days after the race, and reported that soreness and sensations of fatigue and tiredness during training were minimal. Further research examining a heterogeneous sample including slower and faster athletes is needed to establish whether muscle damage might be different according to fitness and/or performance level. This case report is important because it clearly identifies the time points to be investigated in future studies of the time course of muscle damage and recovery from an Ironman triathlon.</p>
    <br />

    <div className="table-container" style={{overflowX: 'auto', margin: '20px 0'}}>
      <h5>Table II: Changes in blood markers week before (pre 1), 24h before (pre 2) and on separate occasions in the 15 days after Ironman triathlon (normal reference ranges are also shown)</h5>
      <table style={{width: '100%', borderCollapse: 'collapse', fontSize: '12px'}}>
        <thead>
          <tr style={{backgroundColor: '#f0f0f0'}}>
            <th style={{border: '1px solid #ccc', padding: '6px', textAlign: 'left'}}>Marker</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>Normal Range</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>Pre 1</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>Pre 2</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>Post</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>2h</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>12h</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>24h</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>2 days</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>3 days</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>4 days</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>5 days</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>8 days</th>
            <th style={{border: '1px solid #ccc', padding: '6px'}}>15 days</th>
          </tr>
        </thead>
        <tbody>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>CK (IU·L⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>50-230</td><td style={{border: '1px solid #ccc', padding: '6px'}}>139</td><td style={{border: '1px solid #ccc', padding: '6px'}}>164</td><td style={{border: '1px solid #ccc', padding: '6px'}}>4990</td><td style={{border: '1px solid #ccc', padding: '6px'}}>5920</td><td style={{border: '1px solid #ccc', padding: '6px'}}>5280</td><td style={{border: '1px solid #ccc', padding: '6px'}}>4590</td><td style={{border: '1px solid #ccc', padding: '6px'}}>1724</td><td style={{border: '1px solid #ccc', padding: '6px'}}>863</td><td style={{border: '1px solid #ccc', padding: '6px'}}>479</td><td style={{border: '1px solid #ccc', padding: '6px'}}>330</td><td style={{border: '1px solid #ccc', padding: '6px'}}>133</td><td style={{border: '1px solid #ccc', padding: '6px'}}>366</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>CK-MM (IU·L⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>44-225</td><td style={{border: '1px solid #ccc', padding: '6px'}}>135</td><td style={{border: '1px solid #ccc', padding: '6px'}}>161</td><td style={{border: '1px solid #ccc', padding: '6px'}}>4889</td><td style={{border: '1px solid #ccc', padding: '6px'}}>5800</td><td style={{border: '1px solid #ccc', padding: '6px'}}>5173</td><td style={{border: '1px solid #ccc', padding: '6px'}}>4497</td><td style={{border: '1px solid #ccc', padding: '6px'}}>1688</td><td style={{border: '1px solid #ccc', padding: '6px'}}>845</td><td style={{border: '1px solid #ccc', padding: '6px'}}>469</td><td style={{border: '1px solid #ccc', padding: '6px'}}>323</td><td style={{border: '1px solid #ccc', padding: '6px'}}>130</td><td style={{border: '1px solid #ccc', padding: '6px'}}>358</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>CK-MB (IU·L⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0-14</td><td style={{border: '1px solid #ccc', padding: '6px'}}>4</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3</td><td style={{border: '1px solid #ccc', padding: '6px'}}>101</td><td style={{border: '1px solid #ccc', padding: '6px'}}>120</td><td style={{border: '1px solid #ccc', padding: '6px'}}>107</td><td style={{border: '1px solid #ccc', padding: '6px'}}>93</td><td style={{border: '1px solid #ccc', padding: '6px'}}>36</td><td style={{border: '1px solid #ccc', padding: '6px'}}>18</td><td style={{border: '1px solid #ccc', padding: '6px'}}>10</td><td style={{border: '1px solid #ccc', padding: '6px'}}>7</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3</td><td style={{border: '1px solid #ccc', padding: '6px'}}>8</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>Myoglobin (μg·mL⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>&lt;85</td><td style={{border: '1px solid #ccc', padding: '6px'}}>27</td><td style={{border: '1px solid #ccc', padding: '6px'}}>33</td><td style={{border: '1px solid #ccc', padding: '6px'}}>4597</td><td style={{border: '1px solid #ccc', padding: '6px'}}>2937</td><td style={{border: '1px solid #ccc', padding: '6px'}}>284</td><td style={{border: '1px solid #ccc', padding: '6px'}}>279</td><td style={{border: '1px solid #ccc', padding: '6px'}}>77</td><td style={{border: '1px solid #ccc', padding: '6px'}}>83</td><td style={{border: '1px solid #ccc', padding: '6px'}}>67</td><td style={{border: '1px solid #ccc', padding: '6px'}}>58</td><td style={{border: '1px solid #ccc', padding: '6px'}}>33</td><td style={{border: '1px solid #ccc', padding: '6px'}}>52</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>AST (IU·L⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>10-40</td><td style={{border: '1px solid #ccc', padding: '6px'}}>28</td><td style={{border: '1px solid #ccc', padding: '6px'}}>27</td><td style={{border: '1px solid #ccc', padding: '6px'}}>136</td><td style={{border: '1px solid #ccc', padding: '6px'}}>172</td><td style={{border: '1px solid #ccc', padding: '6px'}}>191</td><td style={{border: '1px solid #ccc', padding: '6px'}}>216</td><td style={{border: '1px solid #ccc', padding: '6px'}}>148</td><td style={{border: '1px solid #ccc', padding: '6px'}}>107</td><td style={{border: '1px solid #ccc', padding: '6px'}}>75</td><td style={{border: '1px solid #ccc', padding: '6px'}}>79</td><td style={{border: '1px solid #ccc', padding: '6px'}}>33</td><td style={{border: '1px solid #ccc', padding: '6px'}}>30</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>ALT (IU·L⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>5-45</td><td style={{border: '1px solid #ccc', padding: '6px'}}>19</td><td style={{border: '1px solid #ccc', padding: '6px'}}>18</td><td style={{border: '1px solid #ccc', padding: '6px'}}>31</td><td style={{border: '1px solid #ccc', padding: '6px'}}>32</td><td style={{border: '1px solid #ccc', padding: '6px'}}>39</td><td style={{border: '1px solid #ccc', padding: '6px'}}>47</td><td style={{border: '1px solid #ccc', padding: '6px'}}>45</td><td style={{border: '1px solid #ccc', padding: '6px'}}>44</td><td style={{border: '1px solid #ccc', padding: '6px'}}>43</td><td style={{border: '1px solid #ccc', padding: '6px'}}>75</td><td style={{border: '1px solid #ccc', padding: '6px'}}>48</td><td style={{border: '1px solid #ccc', padding: '6px'}}>25</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>LDH (IU·L⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>120-245</td><td style={{border: '1px solid #ccc', padding: '6px'}}>137</td><td style={{border: '1px solid #ccc', padding: '6px'}}>137</td><td style={{border: '1px solid #ccc', padding: '6px'}}>554</td><td style={{border: '1px solid #ccc', padding: '6px'}}>497</td><td style={{border: '1px solid #ccc', padding: '6px'}}>301</td><td style={{border: '1px solid #ccc', padding: '6px'}}>330</td><td style={{border: '1px solid #ccc', padding: '6px'}}>260</td><td style={{border: '1px solid #ccc', padding: '6px'}}>216</td><td style={{border: '1px solid #ccc', padding: '6px'}}>206</td><td style={{border: '1px solid #ccc', padding: '6px'}}>204</td><td style={{border: '1px solid #ccc', padding: '6px'}}>179</td><td style={{border: '1px solid #ccc', padding: '6px'}}>153</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>CRP (mg·dL⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>&lt;0.45</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.04</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.03</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.44</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.75</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.9</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.94</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.83</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.78</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.58</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.42</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.15</td><td style={{border: '1px solid #ccc', padding: '6px'}}>0.08</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>SAA (μg·mL⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>&lt;8</td><td style={{border: '1px solid #ccc', padding: '6px'}}>4.6</td><td style={{border: '1px solid #ccc', padding: '6px'}}>2.7</td><td style={{border: '1px solid #ccc', padding: '6px'}}>59.2</td><td style={{border: '1px solid #ccc', padding: '6px'}}>109.6</td><td style={{border: '1px solid #ccc', padding: '6px'}}>558</td><td style={{border: '1px solid #ccc', padding: '6px'}}>774.5</td><td style={{border: '1px solid #ccc', padding: '6px'}}>933.6</td><td style={{border: '1px solid #ccc', padding: '6px'}}>362.7</td><td style={{border: '1px solid #ccc', padding: '6px'}}>188</td><td style={{border: '1px solid #ccc', padding: '6px'}}>92.6</td><td style={{border: '1px solid #ccc', padding: '6px'}}>26.4</td><td style={{border: '1px solid #ccc', padding: '6px'}}>8.4</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>IL-6 (pg·mL⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>-</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3.31</td><td style={{border: '1px solid #ccc', padding: '6px'}}>2.89</td><td style={{border: '1px solid #ccc', padding: '6px'}}>70.17</td><td style={{border: '1px solid #ccc', padding: '6px'}}>43.01</td><td style={{border: '1px solid #ccc', padding: '6px'}}>9.48</td><td style={{border: '1px solid #ccc', padding: '6px'}}>8.07</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3.97</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3.12</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3.79</td><td style={{border: '1px solid #ccc', padding: '6px'}}>2.41</td><td style={{border: '1px solid #ccc', padding: '6px'}}>2.9</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3.02</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>IL-10 (pg·mL⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>-</td><td style={{border: '1px solid #ccc', padding: '6px'}}>2.57</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3.28</td><td style={{border: '1px solid #ccc', padding: '6px'}}>4.82</td><td style={{border: '1px solid #ccc', padding: '6px'}}>5.32</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3.42</td><td style={{border: '1px solid #ccc', padding: '6px'}}>3.8</td><td style={{border: '1px solid #ccc', padding: '6px'}}>1.93</td><td style={{border: '1px solid #ccc', padding: '6px'}}>2.09</td><td style={{border: '1px solid #ccc', padding: '6px'}}>1.88</td><td style={{border: '1px solid #ccc', padding: '6px'}}>1.86</td><td style={{border: '1px solid #ccc', padding: '6px'}}>2.06</td><td style={{border: '1px solid #ccc', padding: '6px'}}>2.02</td></tr>
          <tr><td style={{border: '1px solid #ccc', padding: '6px'}}>IL-1ra (pg·mL⁻¹)</td><td style={{border: '1px solid #ccc', padding: '6px'}}>-</td><td style={{border: '1px solid #ccc', padding: '6px'}}>497</td><td style={{border: '1px solid #ccc', padding: '6px'}}>801</td><td style={{border: '1px solid #ccc', padding: '6px'}}>17982</td><td style={{border: '1px solid #ccc', padding: '6px'}}>11957</td><td style={{border: '1px solid #ccc', padding: '6px'}}>1353</td><td style={{border: '1px solid #ccc', padding: '6px'}}>1400</td><td style={{border: '1px solid #ccc', padding: '6px'}}>1321</td><td style={{border: '1px solid #ccc', padding: '6px'}}>1229</td><td style={{border: '1px solid #ccc', padding: '6px'}}>510</td><td style={{border: '1px solid #ccc', padding: '6px'}}>442</td><td style={{border: '1px solid #ccc', padding: '6px'}}>986</td><td style={{border: '1px solid #ccc', padding: '6px'}}>694</td></tr>
        </tbody>
      </table>
    </div>

    <h3>Conclusion</h3>
    <p>Although the Ironman triathlon induces a high level of muscle damage characterized by muscle soreness, loss of muscle function, and reductions in aerobic capacity, a well-trained triathlete can recover from this muscle damage within approximately one week. Further studies incorporating large cohorts of Ironman triathletes are necessary to confirm the findings of the present study.</p>

    <h3>References</h3>
    <ul className="references">
      <li>Abbiss, C. R., Peiffer, J. J., Peake, J. M., Nosaka, K., Suzuki, K., Martin, D. T., et al. (2008). Effect of carbohydrate ingestion and ambient temperature on muscle fatigue development in endurance-trained male cyclists. Journal of Applied Physiology, 104, 1021–1028.</li>
      <li>Braun, W. A., & Dutto, D. J. (2003). The effects of a single bout of downhill running and ensuing delayed onset of muscle soreness on running economy performed 48 h later. European Journal of Applied Physiology, 90, 29–34.</li>
      <li>Byrne, C., & Eston, R. (2002). The effect of exercise-induced muscle damage on isometric and dynamic knee extensor strength and vertical jump performance. Journal of Sports Sciences, 20, 417–425.</li>
      <li>Calbet, J. A., Chavarren, J., & Dorado, C. (2001). Running economy and delayed onset muscle soreness. Journal of Sports Medicine and Physical Fitness, 41, 18–26.</li>
      <li>Chen, T. C., Nosaka, K., & Tu, J. H. (2007). Changes in running economy following downhill running. Journal of Sports Sciences, 25, 55–63.</li>
      <li>Farber, H. W., Schaefer, E. J., Franey, R., Grimaldi, R., & Hill, N. S. (1991). The endurance triathlon: Metabolic changes after each event and during recovery. Medicine and Science in Sports and Exercise, 23, 959–965.</li>
      <li>Gaesser, G. A., & Brooks, G. A. (1975). Muscular efficiency during steady-rate exercise: Effects of speed and work rate. Journal of Applied Physiology, 38, 1132–1139.</li>
      <li>Kyröläinen, H., Pullinen, T., Candau, R., Avela, J., Huttunen, P., & Komi, P. V. (2000). Effects of marathon running on running economy and kinematics. European Journal of Applied Physiology, 82, 297–304.</li>
      <li>Lepers, R. (2008). An analysis of Hawaii Ironman performances in elite triathletes from 1981 to 2007. Medicine and Science in Sports and Exercise, 40, 1828–1834.</li>
      <li>Neubauer, O., König, D., & Wagner, K. H. (2008). Recovery after an Ironman triathlon: Sustained inflammatory responses and muscle stress. European Journal of Applied Physiology, 104, 417–426.</li>
      <li>Palazzetti, S., Margaritis, I., & Guezennec, C. Y. (2005). Swimming and cycling overloaded training in triathlon has no effect on running kinematics and economy. International Journal of Sports Medicine, 26, 193–199.</li>
      <li>Paschalis, V., Koutedakis, Y., Baltzopoulos, V., Mougios, V., Jamurtas, A. Z., & Theoharis, V. (2005). The effects of muscle damage on running economy in healthy males. International Journal of Sports Medicine, 26, 827–831.</li>
      <li>Saunders, P. U., Pyne, D. B., Telford, R. D., & Hawley, J. A. (2004). Factors affecting running economy in trained distance runners. Sports Medicine, 34, 465–485.</li>
      <li>Suzuki, K., Peake, J., Nosaka, K., Okutsu, M., Abbiss, C., Surriano, R., et al. (2006). Changes in markers of muscle damage, inflammation and HSP70 after an Ironman triathlon race. European Journal of Applied Physiology, 98, 525–534.</li>
    </ul>

    </div>
);

export default Article1;